services:
  - type: web
    name: grupo-buena-vista
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app_web.py --server.port=$PORT --server.address=0.0.0.0
